### ISSUE TITLE
how can i create single coverage for multiple jasmin test?

### ISSUE THREAD

**Issue by mandalm** [maenu/grunt-template-jasmine-istanbul#57]
if i run coverage for single test then its working file.

Now if i need a single coverage for multiple jasmine test then how can i do that?

```js
jasmine: {
		blocked: {
			src: source,
			options: {
				vendor: [
					'http://code.jquery.com/jquery-1.11.0.js',
					'tests/lib/jasmine-jquery.js',
					'tests/plugins.js',
					"thirdparty.js"
				],
				specs: 'tests/spec/*Blocked.js',
				phantomScript:'phantomjs/script/blockgpt.js',
				template: require('grunt-template-jasmine-istanbul'),
				templateOptions: {
					coverage: 'report/coverage/coverage.json',
					report: 'report/coverage',
				}
			}
		},
		coverage:{
			src: source,
			options: {
				vendor: [
					'http://code.jquery.com/jquery-1.11.0.js',
					'tests/lib/jasmine-jquery.js',
					'tests/plugins.js',
					"thirdparty.js"
				],
				specs: ['tests/spec/*Spec.js'],
				template: require('grunt-template-jasmine-istanbul'),
				templateOptions: {
					coverage: 'report/coverage/coverage.json',
					report: 'report/coverage',
					thresholds: {
						lines: 70,
						statements: 70,
						branches: 50,
						functions: 50
					}
				}
			}
		}
	},
```

please guide me if that is possible with this plug-ins.

regards
Mithun mandal

**Comment by maenu** [comment]
I am not sure if I correctly understand what you intend to do. My understanding is, that you would like to have a single coverage report when you run `grunt jasmine:blocked jasmine:coverage`.
Can you give an example of what you run and what you expect it to behave like?

**Comment by mandalm** [comment]
Hi @maenu I need exactly same what you thought. I need to create a different environment for phantomjs so i need 2 different test. now one test give coverage and other can give a separate coverage. But i needed  a single coverage report. I don't know if that possible with your template. finally i got some other solution which enable a merging coverage report [grunt-istanbul-combine](https://www.npmjs.com/package/grunt-istanbul-combine), how ever i wanted a single solution.

regards
Mithun Mandal

**Comment by maenu** [comment]
I'm glad you found a solution to your problem.

As far is I can tell, there is no way to run two test tasks that generate a single coverage output with this template. See [this code](https://github.com/maenu/grunt-template-jasmine-istanbul/blob/master/src/main/js/template.js#L67) where the coverage data is written: If the coverage file exists, it will be overwritten.
Therefore, I'd suggest outputting the coverage to two different files and using [grunt-istanbul-combine](https://www.npmjs.com/package/grunt-istanbul-combine) to combine them after the tests ran, as you proposed.

As a side-note, I think the current behaviour - where new coverage reports are created for every run - is reasonable, as combining them afterwards turns out not to be that hard. The only issue I see is that the generated coverage data needs to be compatible with the version of istanbul that is used to combine them, but this is inherent through the npm dependency management and I don't see a non-intrusive solution for this problem.

If you are ok with this answer, I'll close the issue.
