### ISSUE TITLE
If spec file have syntax errors it's skipped

### ISSUE THREAD

**Issue by jcubic** [maenu/grunt-template-jasmine-istanbul#60]
I've just notice that when file have errors running `jasmine:coverage` will silently ignore the file with no error indication (I've lost 30 minutes to figure out why my spec is not included). I think that it would be better if there is error of some sort that indicate wrong syntax in a file.

**Comment by maenu** [comment]
Isn't the behavior the same when you run the tests without coverage? I think the issue is that the tests run in PhantomJS. Just like a normal browser it tries to load all sources and throws an error on a broken file. Since it's the spec that has an error, nobody notices this. You can use [grunt-jsvalidate](https://github.com/ariya/grunt-jsvalidate) to make sure all your source files are valid.
