### ISSUE TITLE
Source Maps

### ISSUE THREAD

**Issue by deckar01** [maenu/grunt-template-jasmine-istanbul#61]
I am doing a lot of debugging in the HTML runner that jasmine generates, and am slowed down by the instrumentation injected into the source files.

I am planning to see if I can get a source mapped instrumenter working with this library.

The alternative is running the tests a second time with the coverage template turned off so that jasmine generates a runner with the original source files. That is not desirable, but maybe there is a simpler solution I am not thinking of.

**Comment by maenu** [comment]
Running tests with uninstrumented code for debugging is what I did too in these situations.
Did you make any progress on this? Because it depends heavily on how istanbul instruments the sources. But it seems to be possible somehow, see [this istanbul issue](https://github.com/gotwarlost/istanbul/issues/59).

**Comment by deckar01** [comment]
I did run across that issue, but that use case doesn't quite match up with mine. They were worried about getting 3rd party source maps into the reporter.

I just need istanbul to output a source map for it's instrumentation step.

I dug around a little, but I think it would require modifying istanbul's core instrumentation loop.

Closing for now.
